import {ClerkProvider} from '@clerk/nextjs'
import Header from "@/components/Header";
import {Inter} from "next/font/google";
import "./globals.css";
import { Toaster } from 'sonner';

const inter = Inter({subsets:["latin"]});

export const metadata = {
  title: "My Budget tracker App",
  description: "Generated by create Ashreeta Patra",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        {/* header */}
        <Header/>
        <main className="min-h-screen">
        {children}
        </main>
        <Toaster richColors/>
        {/* footer */}
        <footer className="bg-blue-50 py-12">
          <div className="container mx-auto p-4 text-center text-gray-700">
            <p>Made by Ashreeta Patra</p>
          </div>
        </footer>
      </body>
    </html>
    </ClerkProvider>
  );
}
